language: cpp
compiler: gcc
sudo: false
dist: trusty

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-6 pkg-config uuid-dev libgtest-dev
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7 pkg-config uuid-dev libgtest-dev cmake

script:
############################################################################
# Build main and tests
############################################################################
- mkdir cmake-build-debug
- cd cmake-build-debug
- CXX=/usr/bin/g++-6 CC=/usr/bingcc-6 cmake -DCMAKE_BUILD_TYPE=Debug ..
- cmake