language: cpp
compiler: gcc
dist: trusty

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-7 pkg-config uuid-dev googletest libgtest-dev
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script:
############################################################################
# Build main and tests
############################################################################
- pwd
- cd /usr/src/googletest/googletest
- sudo mkdir build
- cd build
- sudo cmake ..
- sudo make
- sudo cp libgtest* /usr/lib/
- cd ..
- sudo rm -rf build
- cd
- pwd
#- mkdir -p build
#- cd build
#- cmake ${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Debug ..
#- make
#- ctest