language: cpp
compiler: gcc
sudo: false
dist: trusty

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7 pkg-config uuid-dev cmake

script:
############################################################################
# Build main and tests
############################################################################
- mkdir cmake-build-debug
- cd cmake-build-debug
- CXX=/usr/bin/g++-7 CC=/usr/bingcc-7 cmake -DCMAKE_BUILD_TYPE=Debug ..
- cmake